baseURL: "http://rekdalaasen.no/"
languageCode: en-us
title: VRA
theme: PaperMod

enableEmoji: true

params:
  author: Vegard Rekdal Aasen
  homeInfoParams:
    Title: "VRA"
    Content: >
      Welcome to **VRA** 🎉

      - Dette er en testsside

  socialIcons:
    - name: Laget fra
      url: "https://github.com/vegardrekdalaasen"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
