baseURL: "http://rekdalaasen.no/"
languageCode: en-us
title: VRA
theme: PaperMod

enableEmoji: true

params:
  author: Vegard Rekdal Aasen
  homeInfoParams:
    Title: "VRA"
    Content: >
      Welcome to **VRA** 🎉

      - Dette er en testsside

  socialIcons:
    - name: Laget fra
      url: "https://github.com/vegardrekdalaasen"

